columns:
  - Age: int
  - Gender: category
  - Total_Bilirubin: float
  - Direct_Bilirubin: float
  - Alkaline_Phosphotase: int
  - Alamine_Aminotransferase: int
  - Aspartate_Aminotransferas: int
  - Total_Protiens: float
  - Albumin: float
  - Albumin_and_Globulin_Ratio: float
  - liver_disease_YN: int
   

numerical_columns:
  - Age
  - Alkaline_Phosphotase
  - Alamine_Aminotransferase
  - Aspartate_Aminotransferase
  - liver_disease_YN

categorical_columns:
  - Gender


drop_columns:
  - Albumin_and_Globulin_Ratio
  - Aspartate_Aminotransferase

# for data transformation
num_features:
  - Age
  - Total_Protiens
  - Albumin
  - Total_Bilirubin
  -  Direct_Bilirubin
  - Alkaline_Phosphotase
  - Alamine_Aminotransferase


or_columns:
  - Gender


transform_columns:
  - Total_Bilirubin
  - Direct_Bilirubin
  - Alkaline_Phosphotase
  - Alamine_Aminotransferase